### ISSUE TITLE
"property removal" benchmark

### ISSUE THREAD

**Issue by jakobkummerow** [davidmarkclements/v8-perf#11]
https://github.com/davidmarkclements/v8-perf/blob/master/bench/property-removal.js#L16:
`this.x = undefined`
should clearly be:
`obj.x = undefined`

To also make the benchmark representative of arbitrary property deletion (as opposed to the special case of deleting the last property), you can simply add another field in the constructor function:

    function MyClass (x) {
      this.x = x
      this.y = x
    }
(but keep deleting the `x` property).

**Comment by mcollina** [comment]
Thanks! We have updated the post with this suggestion, and we are releasing it asap.
The readme is already updated here.

**Comment by jakobkummerow** [comment]
https://github.com/davidmarkclements/v8-perf/blob/master/bench/property-removal.js#L43 still has the `this.x = ...` bug.

**Comment by jakobkummerow** [comment]
I see you have edited the text to say:

> deleting the last property added to an object hits a fast path in Turbofan

However this has nothing to do with Turbofan.
