### ISSUE TITLE
Duplicate paragraphs

### ISSUE THREAD

**Issue by vsemozhetbyt** [davidmarkclements/v8-perf#14]
It seems the first (old) one is left by mistake:

> In the case of integers (that is, when we specify a number in JS without a decimal), V8 assumes that all numbers are 32bit - until they aren't. This seems like a fair choice, since in many cases a number is within the 0-65535 range. If a JavaScript (whole) number exceeds 65535 the JIT Compiler has to dynamically alter the underlying type for the number to 64bit - this may also have potential knock on effects with regards to other optimizations.
> 
> In the case of integers (that is, when we specify a number in JS without a decimal), V8 assumes that all numbers are 32bit - until they aren’t. This seems like a fair choice, since in many cases a number is within the 2147483648-2147483647 range. If a JavaScript (whole) number exceeds 2147483647 the JIT Compiler has to dynamically alter the underlying type for the number to a double (or: a double-precision floating point number) - this may also have potential knock on effects with regards to other optimizations.

**Comment by mcollina** [comment]
Fixes, thanks!
